### ISSUE TITLE
Question about experiment

### ISSUE THREAD

**Issue by chaofly** [OSUSecLab/SymLM#11]
For the following results in your paper, whether the evaluate model was trained on data from all architectures and all optimization levels, or if each row of results was trained on data from only one architecture and one optimization level

![image](https://github.com/OSUSecLab/SymLM/assets/24863516/c29e52df-c930-487f-b8c4-3f922c744999)

**Comment by xinjin95** [comment]
Hi @chaofly,

For each architecture and optimization level, we train one model and perform evaluations individually.
