### ISSUE TITLE
Model Weights Publication?

### ISSUE THREAD

**Issue by cjchristopher** [OSUSecLab/SymLM#12]
Hi all - thanks for the good work on this paper - I am wondering if it would be possible to get your model weights after the retraining of the Trex model, since we can't source your exact dataset to perform this ourselves?

Regarding this - looking at the codebase, I am a little bit confused, and maybe I have a misunderstanding of fairseq. The architecture of the Trex model (from the fairseq definition of that here: https://github.com/CUMLSec/trex/blob/main/fairseq/models/trex/model.py ) seems very different from the func_name_pred here: https://github.com/OSUSecLab/SymLM/blob/87065740351feeb88cf97f1eead1e6b0e3b65f46/fairseq/models/roberta_mf/function_name_prediction.py#L516 - have I understood this correctly?

**Comment by cjchristopher** [comment]
Apologies - after further inspection of the paper and codebase I think my request is based on a faulty understanding of your architecture. Could you please clarify if my following understanding is right? 

SymLM uses the Trex model only to get their embeddings which you subsequently use to build the Fused Full Function Embedding? (Trex model is never modified/retrained/tuned?)

These embeddings are then your input for a separate fairseq (func_name_pred) decoder model you define for the function name prediction problem (The MLP is Stage 3 of your architecture?), which is targeting the correct function name?

So, the CodeWordNet in Stage 2 is only used in the training and evaluation stages to see if the name predicted is semantically similar to the true name (i.e. controlling for normal variation in naming conventions).

If this model were to be deployed for actual analysis assistance, the CodeWordNet could only be used to suggest what other names the function could have had, correct?

Assuming all this is correct, I guess, is it possible to publish the checkpoint for your final decoder model?? This would be the one that matches the func_name_pred fairseq model defined in the codebase?

**Comment by xinjin95** [comment]
Hi @cjchristopher,

You are right. The two models are not the same. First, the SymLM model contains one encoder and one decoder module. For the encoder module, we took the pre-trained encoder model from Trex. We used MLP as the decoder module. Trex is for function similarity matching which has a different decoder module from ours. Moreover, I observed that Trex's model.py has been updated recently.

For model weights, unfortunately, we didn't keep the model weights as they occupied too much space in our storage. We trained the individual model per architecture and optimization setting, which sums up to dozens of GBs in terms of total size. For our datasets, we released some of them. If you need other datasets, we can find a way to share them with you.
