### ISSUE TITLE
Question about training

### ISSUE THREAD

**Issue by fly1ngpengu1ns** [OSUSecLab/SymLM#15]
Hi, I‘m working on your paper recently, and when I was training with train.sh, I noticed that it stops at 5 epoch and precision is high while recall is low. I was wondering if this is normal since I didn't change the train.sh?
![image](https://github.com/OSUSecLab/SymLM/assets/91705983/c7a89d3d-688c-436a-9277-98f3dadf5f06)

**Comment by fly1ngpengu1ns** [comment]
Besides, I'm a bit confused about the dataset names in data_bin, e.g. byte1~4, arch, inst_pos, what exactly do they stand for? This is probably a really stupid question, but I'm still hoping you can explain it to me

**Comment by xinjin95** [comment]
Hi @fly1ngpengu1ns,

Thanks for your interest. For your first question, the training is bounded by both `TOTAL_UPDATES` and `TOTAL_EPOCHs` in https://github.com/OSUSecLab/SymLM?tab=readme-ov-file#training. Specifically, if `num_updates` reaches `TOTAL_UPDATES` while num_epoch is still under `TOTAL_EPOCHs`, the training process will stop as well. In your screenshot, it looks like your training steps reach the `TOTAL_UPDATES`.

**Comment by xinjin95** [comment]
byte1~4 represents the lowest to highest bytes of numbers, e.g., immediate/hardcoded addresses, in assembly code. arch is the computer architecture. inst_pos is the position of instructions in the binary function. 
For the model input, we inherited the data preprocessing and binarization process of [StateFormer](https://dl.acm.org/doi/10.1145/3468264.3468607). In our code base, you can find this detail [here](https://github.com/OSUSecLab/SymLM/blob/17ea789e11a87c5f14527823fe304fce2c8c74ef/dataset_generation/prepare_dataset.py#L360).

**Comment by fly1ngpengu1ns** [comment]
Got it, thanks for your response
