### ISSUE TITLE
Q for func order in self/input.label and prediction_evaluation/eval_xxx.txt

### ISSUE THREAD

**Issue by LN-Curiosity** [OSUSecLab/SymLM#16]
Thank you for sharing, I have a question. I want the order of the function's test set prediction results **(in training_evaluation/prediction_evaluation)** to be consistent with its **self/input.label**. Does the operation of fairseq-preprocess --testpref change the order of the function? How can I make the two orders consistent?

**Comment by xinjin95** [comment]
To answer your question, the operation of fairseq-preprocess --testpref doesn't change the order of function. During inference/evaluations, we do not perform shuffling.

**Comment by LN-Curiosity** [comment]
> To answer your question, the operation of fairseq-preprocess --testpref doesn't change the order of function. During inference/evaluations, we do not perform shuffling.

Thanks for your response. "--no-shuffle" option in prediction.sh can make the two orders consistent.

**Comment by LN-Curiosity** [comment]
Thanks for your response. "--no-shuffle" option in prediction.sh can make the two orders consistent.
