### ISSUE TITLE
Questions about reproducing the experiment

### ISSUE THREAD

**Issue by Xiaolinger-Z** [OSUSecLab/SymLM#3]
Hello. Thanks for making your great work publicly available.
Here are some questions about the code used in the experiment.

First,  when I run the command "pip install --editable .",  with the following error "ERROR: File "setup.py" not found.  Directory cannot be installed in editable mode". 

Second, when I reproduce the experiment by the command "bash training_evaluation/train.sh", the error is found " can't open file 'train.py': [Errno 2] No such file or directory".  

Is it possible to provide the relevant code? Or can you give some suggestions to help reproduce the experiment?
Again, thanks for your excellent work. I am looking forward to your reply.

**Comment by xinjin95** [comment]
Hi @Xiaolinger-Z ,

Thanks for your interests!

These errors were due to missing some files. The code during submission was sort of unclean, which motivated me to refactor it. However, I forgot to push these files. 

I have fixed them. Let me know if you have more questions.

**Comment by Xiaolinger-Z** [comment]
No more problems, thanks for the fix.
