### ISSUE TITLE
Questions about predict 

### ISSUE THREAD

**Issue by Xiaolinger-Z** [OSUSecLab/SymLM#5]
Hello. Sorry for disturbing you again.
Here are some questions about the name of the prediction function in the experiment.

First, the directory "CodeWordNet" provide the code for model training, but how to use the trained model?

Second,  whether the file "training_evaluation/prediction_evaluation/word_cluster.json"  is related to the model in the first question, and is the file specific to the dataset?

Again, thanks for your excellent work. I am looking forward to your reply.

**Comment by xinjin95** [comment]
Hi @Xiaolinger-Z ,

Thanks for your interests and questions!

The purpose of `CodeWordNet` is to generate word embeddings for semantically matching function names. Specifically, as stated in section 4.3 and 4.4 of our paper, we used it to identify the semantic similar words at inference time. Meanwhile, we observe that the same words can appear again and again. Therefore, to avoid querying `CodeWordNet` repeatedly, we pre-identify the semantically similar words for function name words in our evaluation sets by `CodeWordNet` and save them into `word_cluster.json`.

For your first question, we intended to provide the training code for those who want to train word embeddings with their own dataset (we built `CodeWordNet` based on `CodeSearchNet`).

For your second question, `training_evaluation/prediction_evaluation/word_cluster.json` is specific to our evaluation sets.

Hope these can answer your questions.
