### ISSUE TITLE
Questions about dataset generation

### ISSUE THREAD

**Issue by Direktor799** [OSUSecLab/SymLM#7]
1. Seems like that the output _**icfg.json**_ only has frequence information for callees, but for callers. For example, in _**dataset_generation/icfg/bc/bc/icfg.json**_, `parse_args` appears twice in `main`'s callee, but `main` only appears once in `parse_args`'s caller. It will result in not collecting most frequent caller in **_prepare_dataset.py_**.  Is this intentional?
2. [`byte2seq`](https://github.com/OSUSecLab/SymLM/blob/main/dataset_generation/prepare_dataset.py#L70) took the bytes overlapped and incompleted. Why thisway?
3. The **_generate_vocabulary.py_** mentioned in **_dataset_generation/README.md_** is not found, is it **_get_vocb_for_binarization.py_**?

**Comment by xinjin95** [comment]
Hi @Direktor799 ,

Thank you for your questions! Apologize for the late response.

> 1. Seems like that the output icfg.json only has frequence information for callees, but for callers. For example, in dataset_generation/icfg/bc/bc/icfg.json, parse_args appears twice in main's callee, but main only appears once in parse_args's caller. It will result in not collecting most frequent caller in prepare_dataset.py. Is this intentional?

This is an implementation error. We've fixed it in https://github.com/OSUSecLab/SymLM/commit/7a03132c3e7ce861e5465121232c5c1f54f7d579

> 2. [byte2seq](https://github.com/OSUSecLab/SymLM/blob/main/dataset_generation/prepare_dataset.py#L70) took the bytes overlapped and incompleted. Why thisway?

This function is inherited from the script of pretrained model. 

> 3. The generate_vocabulary.py mentioned in dataset_generation/README.md is not found, is it get_vocb_for_binarization.py?

Thanks for pointing this typo out! We have fixed it.

**Comment by chaofly** [comment]
Hi @xinjin95 ,
After you fix this issue, another issue was introduced.

`File "/home/test/SymLM/dataset_generation/get_calling_context.py", line 83, in get_caller_callee
    res[callee_name]['caller'].append(func_name)
KeyError: '<EXTERNAL>::__cxa_finalize'`


`    while function is not None:
        func_name = function.name
        res[func_name] = {
            'callee': [],
            'caller': []
        }`
Thanks

**Comment by xinjin95** [comment]
Hi @chaofly ,

Thanks for your information. It should be fixed now https://github.com/OSUSecLab/SymLM/commit/a3e92d7123bf444327f42704a4acb17086f829e6 .
