### ISSUE TITLE
false_negative calculate error in evaluate.py

### ISSUE THREAD

**Issue by chaofly** [OSUSecLab/SymLM#8]
false_negative shoud be `len(target.difference(prediction))`, but it is `len(prediction.difference(target))` in 
[evalute.py](https://github.com/OSUSecLab/SymLM/blob/main/training_evaluation/evaluation.py).
In [criterions/function_name_prediction.py](https://github.com/OSUSecLab/SymLM/blob/main/fairseq/criterions/function_name_prediction.py), `false_negative = ((targets == 1) * (preds == 0)).sum()`

For example, let target be `set(['b', 'c', 'e'])`, prediction be `set(['a', 'c'])`, the result of  `len(prediction.difference(target))` is `len(set('a'))=1`. For one-hot encoding, target is `[0,1,1,0,1]`, prediction is `[1,0,1,0,0]`, the result of `false_negative = ((targets == 1) * (preds == 0)).sum()` is `(tensor([false,true,true,false,true])*tensor([false,true,false,true,true])).sum() = 2`

**Comment by xinjin95** [comment]
Hi @chaofly,

Thanks for pointing out this refactoring error! We have fixed it.

**Comment by chaofly** [comment]
Hi @xinjin95,

Thanks for your response, I have another question about this issue.
 
In [SymLM github main page](https://github.com/OSUSecLab/SymLM), the `Recall` is higher than `Precious` with error [evaluation.py](https://github.com/OSUSecLab/SymLM/blob/main/training_evaluation/evaluation.py)
`Probability Threshold = 0.3, Precision: 0.4968238162277238, Recall: 0.7111646309994839, F1: 0.584978319536674`
In your paper, `Recall` is also higher than `Precious`, so whether the correct result of your model should be that `Precious` is higher than `Recall`

**Comment by xinjin95** [comment]
The precision, recall, and F1 score are dynamic based on the threshold. It depends on the specific tasks. 
When we evaluated the model, we chose different thresholds to get the best performance.
