### ISSUE TITLE
Question about dataset_generation for ARM, MIPS architecture

### ISSUE THREAD

**Issue by chaofly** [OSUSecLab/SymLM#9]
In [get_calling_context.py (line 68)](https://github.com/OSUSecLab/SymLM/blob/main/dataset_generation/get_calling_context.py), the code use 'CALL' to judge function calls is only suitable for x86 and x64. In ARM, the instructions of function calls are bl, blx, bx, and in MIPS, the instructions of function calls are jal
![image](https://github.com/OSUSecLab/SymLM/assets/24863516/45780215-652a-4c47-8e90-69fb09be31e9)

**Comment by xinjin95** [comment]
Thanks for pointing out this problem. This should have been fixed in: https://github.com/OSUSecLab/SymLM/commit/34d86a5aff431629ff838e6e6478caece1ee399c
